version: "3.9"

services:
  authentification:
    build: ./authentification
    networks:
      my_network:
        ipv4_address: 192.168.0.3
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
        DB_USER: admin
        DB_PASSWORD: adminpass
        DB_URL: 192.168.0.2:3306
        DB_DATABASE: app_news
        ORIGINS_URL: http://localhost:8080
        JWT_SECRET_KEY: 8bf194eca505a14a48a079410fdbd100

  backend:
    build: ./backend
    networks:
      my_network:
        ipv4_address: 192.168.0.4
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_URL: 192.168.0.2:3306
      DB_DATABASE: app_news
      ORIGINS_URL: http://localhost:8080
      JWT_SECRET_KEY: 8bf194eca505a14a48a079410fdbd100
  db:
      build: ./mysql_articles
      networks:
        my_network:
          ipv4_address: 192.168.0.2
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: app_news
        MYSQL_USER: admin
        MYSQL_PASSWORD: adminpass
      volumes:
        - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.0.5
    ports:
      - 9090:8080

  frontend:
    build: ./frontend
    networks:
      my_network:
        ipv4_address: 192.168.0.6
    ports:
      - "8080:8080"
    environment:
      VUE_APP_BACKEND_URL: http://127.0.0.1:8000
      VUE_APP_AUTH_URL: http://127.0.0.1:8001

volumes:
    mysql-data:

networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.0.0/24
