apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pashadigori2000/cloud-computing:frontend-image-v20
        ports:
        - containerPort: 80
        env:
          - name: VUE_APP_AUTH_URL
            value: http://authentification-service:8001
          - name: VUE_APP_BACKEND_URL
            value: http://backend-service:8000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
#  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
#    nodePort: 30121
