kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim  # Sets name of PVC
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size