-- create the first database and user
CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE_1}`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_1}.* TO '${MYSQL_USER_1}'@'%';

-- create the second database and user
CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE_2}`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_2}.* TO '${MYSQL_USER}'@'%';

-- FLUSH PRIVILEGES ensures that the changes made will take effect immediately.
FLUSH PRIVILEGES;
